name: TypeScript check

on:
    push:

jobs:
    tsc:
        permissions:
            contents: read
            packages: read

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [22.x]

        steps:
            - name: ðŸ”¨ checkout repository
              uses: actions/checkout@v4
            - name: ðŸ”¨ use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: ðŸ”¨ install package dependencies
              run: npm install
            - name: ðŸ”¨ run typescript check
              run: tsc
